# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IbToolPartition
                                 A QGIS plugin
 This tool generates a partition of the dataset based on building footprints.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-15
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Oliver Harig
        email                : ottmar.hittzfeld@web.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import (
    QgsProject,
    Qgis,
    QgsApplication,
    QgsProcessingFeedback,
    QgsVectorLayer,
    QgsRasterLayer,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFileDestination,
    QgsProcessingUtils
)
from qgis import processing

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .IbToolPartion_dialog import IbToolPartitionDialog
import os.path


class IbToolPartition:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IbToolPartition_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&IB-Tool (Partitioning)')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IbToolPartition', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/IbToolPartion/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'IB-Tool (Partitioning)'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IB-Tool (Partitioning)'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self.dlg, "Select   output file ", "", '*.shp')
        self.dlg.output_file.setText(filename)

    def select_input_file(self):  # Petersen
        filename, _filter = QFileDialog.getOpenFileName(
            self.dlg, "Select input file ", "", '*.shp')
        self.dlg.Input_HU.setText(filename)


    def siedgr(self, input_hu, cell_size, filename):
        feedback = QgsProcessingFeedback()
        feedback.pushInfo("Start partitioning")

        # Variablen
        radius = 2 * cell_size

        # Output-Dateien (temporär)
        input_feature_point = QgsProcessingUtils.generateTempFilename("input_feature_point.gpkg")
        hu_raster = QgsProcessingUtils.generateTempFilename("hu_raster.tif")
        hu_raster_feature = QgsProcessingUtils.generateTempFilename("hu_raster_feature.gpkg")
        thiess_poly = QgsProcessingUtils.generateTempFilename("thiess_poly.gpkg")
        thiess_diss= QgsProcessingUtils.generateTempFilename("thiess_diss.gpkg")
        thiess_diss_line = QgsProcessingUtils.generateTempFilename("thiess_diss_line.gpkg")
        thiess_line = QgsProcessingUtils.generateTempFilename("thiess_line.gpkg")
        thiess_split = QgsProcessingUtils.generateTempFilename("thiess_split.gpkg")
        merge = QgsProcessingUtils.generateTempFilename("merge.gpkg")
        poly_grenz = QgsProcessingUtils.generateTempFilename("poly_grenz.gpkg")


        # Feature-to-Point
        processing.run(
            "native:centroids",
            {
                "INPUT": input_hu,
                "ALL_PARTS": False,
                "OUTPUT": input_feature_point
            },
            feedback=feedback
        )

        # Punktdichte erstellen
        processing.run("qgis:heatmapkerneldensityestimation",
                       {'INPUT': input_feature_point,
                        'RADIUS': radius,
                        'RADIUS_FIELD': '',
                        'PIXEL_SIZE': cell_size,
                        'WEIGHT_FIELD': '',
                        'KERNEL': 0,
                        'DECAY': 0,
                        'OUTPUT_VALUE': 0,
                        'OUTPUT': hu_raster}
                                )

        # Raster-to-Point
        processing.run("native:pixelstopoints", {
            'INPUT_RASTER': hu_raster,
            'RASTER_BAND': 1,
            'FIELD_NAME': 'VALUE',
            'OUTPUT': hu_raster_feature},
            feedback= feedback
        )

        # Thiessen-Polygone erstellen
        processing.run(
            "native:voronoipolygons",
            {
                "INPUT": hu_raster_feature,
                "OUTPUT": thiess_poly
            },
            feedback=feedback
        )

        processing.run("native:dissolve", {
            'INPUT': thiess_poly,
            'FIELD': [], 'SEPARATE_DISJOINT': False, 'OUTPUT': thiess_diss})

        processing.run("native:polygonstolines", {
            'INPUT': thiess_diss,
            'OUTPUT': thiess_diss_line})

        # Polygone zu Linien
        processing.run(
            "native:polygonstolines",
            {
                "INPUT": thiess_poly,
                "OUTPUT": thiess_line
            },
            feedback=feedback
        )

        # Linien teilen
        processing.run(
            "native:explodelines",
            {
                'INPUT': thiess_line,
                'OUTPUT': thiess_split
            },
            feedback=feedback
         )

        radius_del = cell_size // 2 + 10

        # Layer laden
        layer = QgsVectorLayer(thiess_split, "Split Lines", "ogr")

        if not layer.isEditable():
                layer.startEditing()

        # Features in einer bestimmten Entfernung auswählen und löschen
        processing.run(
            "native:selectwithindistance",
            {
                'INPUT': layer,
                'REFERENCE': hu_raster_feature,
                'DISTANCE': radius_del,
                'METHOD': 0
             },
            feedback=feedback
        )

        # IDs der ausgewählten Features holen
        feature_ids = [feature.id() for feature in layer.selectedFeatures()]

        if feature_ids:
            # Ausgewählte Features löschen
            layer.deleteFeatures(feature_ids)
            feedback.pushInfo(f"{len(feature_ids)} Feature(s) wurden gelöscht.")
        else:
            feedback.pushInfo("Keine Features zur Löschung ausgewählt.")

        # Änderungen speichern
        layer.commitChanges()

        processing.run("native:mergevectorlayers",
                       {'LAYERS': [layer, thiess_diss_line], 'CRS': None,
                        'OUTPUT': merge})

        # Linien zu Polygonen
        processing.run(
            "native:polygonize",
            {   'INPUT': merge,
                'KEEP_FIELDS': False,
                'OUTPUT': poly_grenz
            },
            feedback = feedback
        )

        # Name-Feld hinzufügen
        processing.run("native:fieldcalculator", {
            'INPUT': poly_grenz,
            'FIELD_NAME': 'NAME', 'FIELD_TYPE': 2, 'FIELD_LENGTH': 0, 'FIELD_PRECISION': 0, 'FORMULA': "'PART_' || $id",
            'OUTPUT': filename})

        return filename


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = IbToolPartitionDialog()
            self.dlg.HU_Button.clicked.connect(self.select_input_file)
            self.dlg.Output_Button.clicked.connect(self.select_output_file)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            input_hu_path = self.dlg.Input_HU.text()
            
            # Validierung der Eingabedatei
            if not input_hu_path or not os.path.exists(input_hu_path):
                self.iface.messageBar().pushMessage(
                    "Error", "Bitte wählen Sie eine gültige Eingabedatei aus.",
                    level=Qgis.Critical, duration=5)
                return
            
            # Erstelle QgsVectorLayer aus dem Pfad (falls nötig für Spatial Index)
            input_layer = QgsVectorLayer(input_hu_path, "input_layer", "ogr")
            if input_layer.isValid():
                # Spatial Index erstellen falls gewünscht
                input_layer.dataProvider().createSpatialIndex()
            
            cell_size_text = self.dlg.cell_size.text()
            try:
                cell_size = int(cell_size_text)  # Konvertiere den Text in eine Zahl
                print(f"Eingegebener Wert als Zahl: {cell_size}")
            except ValueError:
                self.iface.messageBar().pushMessage(
                    "Error", "Ungültiger Zahlenwert für Zellgröße eingegeben.",
                    level=Qgis.Critical, duration=5)
                return

            filename = self.dlg.output_file.text()
            
            # Validierung der Ausgabedatei
            if not filename:
                self.iface.messageBar().pushMessage(
                    "Error", "Bitte wählen Sie eine Ausgabedatei aus.",
                    level=Qgis.Critical, duration=5)
                return

            # Übergebe den Pfad an die siedgr Methode (nicht das Layer-Objekt)
            out_siedgr = self.siedgr(input_hu_path, cell_size, filename)

            self.iface.messageBar().pushMessage(
                "Success", "Output file written at " + out_siedgr,
                level=Qgis.Success, duration=3)