# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IbToolPartition
                                 A QGIS plugin
 This tool generates a partition of the dataset based on building footprints.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-15
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Oliver Harig
        email                : ottmar.hittzfeld@web.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# pylint: disable=import-error
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import (
    Qgis,
    QgsProcessingFeedback,
    QgsVectorLayer,
    QgsProcessingUtils,
)
from qgis import processing

from .resources import *  # noqa: F401,F403  # pylint: disable=wildcard-import,unused-wildcard-import
from .IbToolPartion_dialog import IbToolPartitionDialog
import os.path


class IbToolPartition:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            f'IbToolPartition_{locale}.qm')

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&IB-Tool')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IbToolPartition', message)

    def add_action(  # pylint: disable=too-many-arguments
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = ':/plugins/IbToolPartion/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Partitioning'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IB-Tool'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_output_file(self):
        """Open a save-file dialog and write the chosen path to the dialog."""
        if not hasattr(self, 'dlg') or self.dlg is None:
            return

        filename, _filter = QFileDialog.getSaveFileName(
            self.dlg,
            self.tr("Select output file"),
            "",
            self.tr('Shapefiles (*.shp);;GeoPackage (*.gpkg);;All Files (*)')
        )

        if filename:
            self.dlg.output_file.setText(filename)

    def select_input_file(self):
        """Open an open-file dialog and write the chosen path to the dialog."""
        filename, _filter = QFileDialog.getOpenFileName(
            self.dlg, self.tr("Select input file"),
            "", self.tr('Vector files (*.shp *.gpkg)'))
        self.dlg.Input_HU.setText(filename)

    def siedgr(self, input_hu, cell_size, filename):  # pylint: disable=too-many-locals
        """Run the partitioning algorithm and return the output path."""
        feedback = QgsProcessingFeedback()
        feedback.pushInfo(self.tr("Start partitioning"))

        radius = 2 * cell_size

        input_feature_point = QgsProcessingUtils.generateTempFilename(
            "input_feature_point.gpkg")
        hu_raster = QgsProcessingUtils.generateTempFilename("hu_raster.tif")
        hu_raster_feature = QgsProcessingUtils.generateTempFilename(
            "hu_raster_feature.gpkg")
        thiess_poly = QgsProcessingUtils.generateTempFilename("thiess_poly.gpkg")
        thiess_diss = QgsProcessingUtils.generateTempFilename("thiess_diss.gpkg")
        thiess_diss_line = QgsProcessingUtils.generateTempFilename(
            "thiess_diss_line.gpkg")
        thiess_line = QgsProcessingUtils.generateTempFilename("thiess_line.gpkg")
        thiess_split = QgsProcessingUtils.generateTempFilename("thiess_split.gpkg")
        merge = QgsProcessingUtils.generateTempFilename("merge.gpkg")
        poly_grenz = QgsProcessingUtils.generateTempFilename("poly_grenz.gpkg")

        processing.run(
            "native:centroids",
            {
                "INPUT": input_hu,
                "ALL_PARTS": False,
                "OUTPUT": input_feature_point
            },
            feedback=feedback
        )

        processing.run("qgis:heatmapkerneldensityestimation",
                       {'INPUT': input_feature_point,
                        'RADIUS': radius,
                        'RADIUS_FIELD': '',
                        'PIXEL_SIZE': cell_size,
                        'WEIGHT_FIELD': '',
                        'KERNEL': 0,
                        'DECAY': 0,
                        'OUTPUT_VALUE': 0,
                        'OUTPUT': hu_raster})

        processing.run("native:pixelstopoints", {
            'INPUT_RASTER': hu_raster,
            'RASTER_BAND': 1,
            'FIELD_NAME': 'VALUE',
            'OUTPUT': hu_raster_feature},
            feedback=feedback
        )

        processing.run(
            "native:voronoipolygons",
            {
                "INPUT": hu_raster_feature,
                "OUTPUT": thiess_poly
            },
            feedback=feedback
        )

        processing.run("native:dissolve", {
            'INPUT': thiess_poly,
            'FIELD': [], 'SEPARATE_DISJOINT': False, 'OUTPUT': thiess_diss})

        processing.run("native:polygonstolines", {
            'INPUT': thiess_diss,
            'OUTPUT': thiess_diss_line})

        processing.run(
            "native:polygonstolines",
            {
                "INPUT": thiess_poly,
                "OUTPUT": thiess_line
            },
            feedback=feedback
        )

        processing.run(
            "native:explodelines",
            {
                'INPUT': thiess_line,
                'OUTPUT': thiess_split
            },
            feedback=feedback
        )

        radius_del = cell_size // 2 + 10

        layer = QgsVectorLayer(thiess_split, "Split Lines", "ogr")

        if not layer.isEditable():
            layer.startEditing()

        processing.run(
            "native:selectwithindistance",
            {
                'INPUT': layer,
                'REFERENCE': hu_raster_feature,
                'DISTANCE': radius_del,
                'METHOD': 0
            },
            feedback=feedback
        )

        feature_ids = [feature.id() for feature in layer.selectedFeatures()]

        if feature_ids:
            layer.deleteFeatures(feature_ids)
            feedback.pushInfo(self.tr("{} feature(s) deleted.").format(len(feature_ids)))
        else:
            feedback.pushInfo(self.tr("No features selected for deletion."))

        layer.commitChanges()

        processing.run("native:mergevectorlayers",
                       {'LAYERS': [layer, thiess_diss_line], 'CRS': None,
                        'OUTPUT': merge})

        processing.run(
            "native:polygonize",
            {'INPUT': merge,
             'KEEP_FIELDS': False,
             'OUTPUT': poly_grenz},
            feedback=feedback
        )

        processing.run("native:fieldcalculator", {
            'INPUT': poly_grenz,
            'FIELD_NAME': 'NAME', 'FIELD_TYPE': 2, 'FIELD_LENGTH': 0,
            'FIELD_PRECISION': 0, 'FORMULA': "'PART_' || $id",
            'OUTPUT': filename})

        return filename

    def run(self):
        """Run method that performs all the real work."""
        if self.first_start:
            self.first_start = False
            self.dlg = IbToolPartitionDialog()  # pylint: disable=attribute-defined-outside-init
            self.dlg.HU_Button.clicked.connect(self.select_input_file)
            self.dlg.Output_Button.clicked.connect(self.select_output_file)

        self.dlg.show()
        result = self.dlg.exec_()
        if result:
            input_hu_path = self.dlg.Input_HU.text()

            if not input_hu_path or not os.path.exists(input_hu_path):
                self.iface.messageBar().pushMessage(
                    self.tr("Error"), self.tr("Please select a valid input file."),
                    level=Qgis.Critical, duration=5)
                return

            input_layer = QgsVectorLayer(input_hu_path, "input_layer", "ogr")
            if input_layer.isValid():
                input_layer.dataProvider().createSpatialIndex()

            cell_size_text = self.dlg.cell_size.text()
            try:
                cell_size = int(cell_size_text)
                print(f"Cell size value: {cell_size}")
            except ValueError:
                self.iface.messageBar().pushMessage(
                    self.tr("Error"), self.tr("Invalid numeric value for cell size."),
                    level=Qgis.Critical, duration=5)
                return

            filename = self.dlg.output_file.text()

            if not filename:
                self.iface.messageBar().pushMessage(
                    self.tr("Error"), self.tr("Please select an output file."),
                    level=Qgis.Critical, duration=5)
                return

            out_siedgr = self.siedgr(input_hu_path, cell_size, filename)

            self.iface.messageBar().pushMessage(
                self.tr("Success"), self.tr("Output file written at {}").format(out_siedgr),
                level=Qgis.Success, duration=3)
