[tool:pytest]
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --verbose
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning